server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirige les routes inconnues vers index.html (Vital pour React)
        try_files $uri $uri/ /index.html;
    }
}